# Generated by Django 5.1.6 on 2025-03-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='capacity',
            field=models.IntegerField(blank=True, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='deposit_number',
            field=models.BigIntegerField(verbose_name='Número Depósito'),
        ),
    ]
