# Generated by Django 5.1.6 on 2025-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_alter_permit_capacity_alter_permit_deposit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_mode',
            field=models.CharField(choices=[('TR', 'Transporte'), ('OC', 'Ocasional'), ('CN', 'Construcción'), ('FN', 'Funcionamiento')], default='TR', max_length=2, verbose_name='Modo Permiso'),
        ),
    ]
