# Generated by Django 5.1.6 on 2025-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=128, verbose_name='Apellido')),
                ('national_id', models.CharField(max_length=15, verbose_name='Cédula')),
                ('active', models.BooleanField(default=True, verbose_name='Habilitado')),
            ],
        ),
    ]
