# Generated by Django 5.1.6 on 2025-02-28 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermitTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('active', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Creación')),
            ],
        ),
    ]
