# Generated by Django 5.1.6 on 2025-02-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittypes',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
