# Generated by Django 5.1.6 on 2025-03-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit_types', '0002_alter_permittypes_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermitTypes',
            new_name='PermitType',
        ),
    ]
